### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by blakemcbride** [rhaberkorn/sciteco#11]
[...]
Info: Removed file "/home/blake/Backup/sciteco.git/src/symbols-scintilla.c" from the ring
Info: Removed file "/home/blake/Backup/sciteco.git/src/undo.c" from the ring
Info: Removed file "/home/blake/Backup/sciteco.git/src/view.c" from the ring
../src/sciteco-minimal -e $'EBsciteco.7.in\e <FS@PACKAGE^Q@\esciteco\e;>J <FS@PACKAGE_NAME^Q@\eSciTECO\e;>J <FS@PACKAGE_VERSION^Q@\e2.0.0\e;>J <FS@PACKAGE_URL^Q@\ehttp://sciteco.sf.net/\e;>J <FS@PACKAGE_URL_DEV^Q@\ehttps://github.com/rhaberkorn/sciteco\e;>J <FS@bindir^Q@\e/usr/local/bin\e;>J <FS@libexecdir^Q@\e/usr/local/libexec\e;>J <FS@pkgdatadir^Q@\e/usr/local/share/sciteco\e;>J <FS@scitecolibdir^Q@\e/usr/local/share/sciteco/lib\e;>J <FS@TECO_INTEGER^Q@\e64\e;>J <FS@DATE^Q@\e19 Nov 2022\e; -D>J EWsciteco.7\e'
Info: Added new unnamed file to ring.
Info: Added file "sciteco.7.in" to ring
groff -wall -Z -Tascii -t -man -M. -msciteco grosciteco.tes.1 >grosciteco.tes.1.intermediate
../src/sciteco -m -- ./grosciteco.tes \
                grosciteco.tes.1.woman grosciteco.tes.1.intermediate
Info: Added new unnamed file to ring.
Info: Added file "grosciteco.tes.1.intermediate" to ring
Error: Invalid Q-Register "default-style"
Info: #0 in Q-Register "format" at 6819 (396:30)
Info: #1 in file "./grosciteco.tes" at 5195 (256:10)
make[2]: *** [GNUmakefile:818: grosciteco.tes.1.woman] Error 1
rm sciteco.7.in grosciteco.tes.1.intermediate
make[2]: Leaving directory '/home/blake/Backup/sciteco.git/doc'
make[1]: *** [GNUmakefile:506: all-recursive] Error 1
make[1]: Leaving directory '/home/blake/Backup/sciteco.git'
make: *** [GNUmakefile:415: all] Error 2

**Comment by rhaberkorn** [comment]
Hello!

Please type the following in your build directory:
```
cd doc
make grosciteco.tes.1.intermediate
```

And send me the file `grosciteco.tes.1.intermediate`.
I would also be interested in your Groff version (`groff --version`).

**Comment by rhaberkorn** [comment]
I've fixed my nightly builds. Tomorrow, there will also be binaries to download here:
https://nightly.link/rhaberkorn/sciteco/workflows/nightly/master

I don't like that all artifacts get lost in 90 days if I do not fix my Github action workflows. Will probably switch to a scheme where nightly builds are automatically uploaded as Github releases. In this case, there will always be an archive of last builds.

**Comment by rhaberkorn** [comment]
Nightly builds can from now on be found here:
https://github.com/rhaberkorn/sciteco/releases/tag/nightly

Did you have any luck?

**Comment by blakemcbride** [comment]
As of April 4, 2023, SCITECO still cannot be built on Linux.

**Comment by blakemcbride** [comment]
Attached is grosciteco.tes.1.intermediate

$ groff -version
GNU groff version 1.23.0.rc1.3397-37c6e
Copyright (C) 2022 Free Software Found
[grosciteco.tes.1.intermediate.zip](https://github.com/rhaberkorn/sciteco/files/11149198/grosciteco.tes.1.intermediate.zip)
ation, Inc.
GNU groff comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of groff and its subprograms
under the terms of the GNU General Public License.
For more information about these matters, see the file
named COPYING.

called subprograms:

GNU troff (groff) version 1.23.0.rc1.3397-37c6e
GNU eqn (groff) version 1.23.0.rc1.3397-37c6e
GNU grops (groff) version 1.23.0.rc1.3397-37c6e

**Comment by rhaberkorn** [comment]
It should build now. But I am not sure, that the generated files look well. Could you send me your `doc/grosciteco.tes.1.woman` and `doc/grosciteco.tes.1.woman.tec` files please?

**Comment by rhaberkorn** [comment]
Thanks! Everything looks fine now.

**Comment by blakemcbride** [comment]
Will do.  Thanks!
